server:
  port: 8761
spring:
  application:
    name: eurekaserver
  profiles:
    active: dev
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
    client:
      ip-address: 127.0.0.1
eureka:
  server:
    # 服务节点连接超时时间
    peer-node-read-timeout-ms: 3000
    # 是否开启自我保护，默认开启，开启后注册中心丢失客户端时会进入自我保护模式，心跳失败时并不会从注册中心删掉该服务，推荐false
    enable-self-preservation: false
  instance:
    # 是否注册自己
    prefer-ip-address: true
    # 注册显示的实例id
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 自定义服务名，默认hostname
    hostname: eurekaserver
  client:
    registerWithEureka: true
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      # 注册中心默认地址
      defaultZone: http://127.0.0.1:8761/eureka/